---
linux: 
  children: 
    nginx_proxies: # Имя подгруппы хостов
      hosts: # Узлы группы
        Nginx-proxy: # Проксирующий сервер
          ansible_host: 51.250.79.101 # Адрес проксирующего Nginx
          ansible_ssh_private_key_file: "~/.ssh/id_ed25519"
    nginx_servers:
      hosts:
        Nginx-server1: # Отдающий сервер 1
          ansible_host: 62.84.116.185 # Адрес отдающего Nginx №1
          ansible_ssh_private_key_file: "~/.ssh/id_ed25519"
        Nginx-server2: # Отдающий сервер 2
          ansible_host: 62.84.126.106 # Адрес отдающего Nginx №2
          ansible_ssh_private_key_file: "~/.ssh/id_ed25519"
  vars: # Переменные, доступные или используемые для всех подгрупп
    ansible_user: "svaips"
    connection_protocol: ssh # Тип подключения
    ansible_become: true # Становиться ли другим пользователем после подключения
    ansible_become_method: sudo
