---
- name: Установка Nginx
  apt:
    name: nginx
    state: present

- name: Настройка прокси
  template:
    src: proxy.conf.j2
    dest: /etc/nginx/sites-available/proxy

- name: Создание символической ссылки
  command: ln -s /etc/nginx/sites-available/proxy /etc/nginx/sites-enabled/proxy
  args:
    removes: /etc/nginx/sites-enabled/proxy

- name: Перезапуск Nginx
  service:
    name: nginx
    state: restarted
